### ISSUE TITLE
Support for other NER datasets

### ISSUE THREAD

**Issue by stefan-it** [neulab/InterpretEval#1]
Hi,

I really enjoyed reading the paper (great analysis and good attributes for NER tasks) and love the idea of both a leaderboard with detailed information and comparisons between other models :heart: 

So I would like to ask, if you do plan to add support for other NER datasets like e.g. CoNLL-2003 (German, both the revisited and the original dataset), CoNLL-2002 (Spanish and Dutch) or even GermEval 2014 (which is an awesome resource for German NER).

I would love to provide you the output of our systems that we've trained for the CoNLL datasets (see paper [here](https://arxiv.org/abs/2011.06993) with Alan from Flair) and for GermEval (see paper [here](https://arxiv.org/abs/2010.10906) with the people from Deepset).

Additionally, there's a corrected version of the English CoNLL coming soon (see [here](https://www.aclweb.org/anthology/2020.conll-1.16/)) and adding support for it on the ExplainaBoard would be really awesome (to compare the "uncorrected" vs. corrected dataset).

Many thanks for the great work!

Stefan

**Comment by pfliu-nlp** [comment]
Hi, Stefan, thanks for your interest and nice words!
I just checked the ExplainaBoard website; it seems that there is some problem with the "uploaded service." But no worries, could you please send your output file with me (stefanpengfei@gmail.com) together with the corresponding papers? We will (1) perform analysis on it; and add it to ExplainaBoard, (3) and let you know.

**Comment by stefan-it** [comment]
Thanks for your reply! Mail is out now :hugs:

**Comment by pfliu-nlp** [comment]
Done. Please check your models and corresponding interpretable analysis: http://explainaboard.nlpedia.ai/?search=CoNLL
 Also, congratulations on your excellent performance on the NER CoNLL03 dataset.
![image](https://user-images.githubusercontent.com/59123869/100667781-f4944c00-3328-11eb-815a-874700c7624c.png)
![image](https://user-images.githubusercontent.com/59123869/100667853-0b3aa300-3329-11eb-8171-7dc52ba9df3e.png)

**Comment by neubig** [comment]
This is now supported, both in explainaboard and in this code and documentation.
