### ISSUE TITLE
How to upload the model predictions?

### ISSUE THREAD

**Issue by ikuyamada** [neulab/InterpretEval#2]
Hi,
I could not figure out how to upload the file containing model predictions to ExplainaBoard.
I have a NER model for the CoNLL-2003 dataset and also a file containing its dev and test predictions.
Is it possible to analyze our model by submitting the test predictions to ExplainaBoard?
Thanks.

**Comment by stefan-it** [comment]
Hi @ikuyamada ,

I would also like to upload the predictions for our models, see #1 😁

I managed to register a new account (just have a look at the header from latest explainaboard site). Then I was able to create a new entry, but the upload of a prediction file did not work, it shows an error on server side.

For prediction format is used the same as provided in the `result` folder of this repo, see [here](https://github.com/neulab/InterpretEval/tree/master/interpretEval/preComputed/ner/result).

Hopefully the authors can help here :hugs:

**Comment by stefan-it** [comment]
Oh, and congrats for the LUKE paper :+1: (we'll add the LUKE results to our paper mentioned in #1, in the next iteration/update!)

**Comment by ikuyamada** [comment]
Hi @stefan-it,
Thanks😄 
Also, I did the exact same procedure on the Explainaboard site and ended up with the server error.

**Comment by pfliu-nlp** [comment]
Aha,  Ikuya, thanks for your interest! 
Could you please send your output file with me (stefanpengfei@gmail.com) together with the corresponding papers? We will (1) perform analysis on it; and add it to ExplainaBoard, (3) and let you know.
(BTW,  the "uploaded service" of ExplainaBoard will be available next week lol)

**Comment by ikuyamada** [comment]
Thanks! I will send the output files later👍

**Comment by jlfu** [comment]
Hi, @ikuyamada,
I found that the result file of LUKE is not a standard BIO/BIOES format. Could you convert the result file into BIO format, and send it to me (fujl16@fudan.edu.cn)? Thank you!

**Comment by ikuyamada** [comment]
Hi @jlfu, It seems that the result file is processed by the official evaluation script (`conlleval.pl`) without issues. Would you please provide an example of invalid lines in the result file?
Also, the result file is in the IOB1 format. Do I need to convert the file to IOB2?

**Comment by jlfu** [comment]
Ok, i got it.
We can convert the file from BIO1 to BIO2.
Thank you!

**Comment by ikuyamada** [comment]
@jlfu Thanks!
