### ISSUE TITLE
"sz" command not found

### ISSUE THREAD

**Issue by neubig** [neulab/InterpretEval#4]
Upon running `run_ner.sh` I get the following error near the end of the script (https://github.com/neulab/InterpretEval/blob/master/interpretEval/run_task_ner.sh#L94):

    run_task_ner.sh: line 96: sz: command not found

I'm not sure what the "sz" command does, or where to find it. Could you elaborate?

**Comment by jlfu** [comment]
It seems to lack a package named `lrzsz`. You can install the package use this command:   `yum install lrzsz`.

**Comment by neubig** [comment]
Thanks! I'm using a mac, where this package is not installed by default. Could you also add that to the documentation?

I'm also curious what this command is actually doing. Is it necessary?

**Comment by jlfu** [comment]
Thanks for pointing it out. I think we can delete commands from line 94 to line 96 since these commands are not necessary to generate the webpage.

**Comment by neubig** [comment]
This is now commented out, thanks @jlfu!
https://github.com/neulab/InterpretEval/blob/master/interpretEval/run_task_ner.sh
