### ISSUE TITLE
Some pre-computed features not available, causing crashes

### ISSUE THREAD

**Issue by neubig** [neulab/InterpretEval#6]
Hi,

I'm trying to run on a new dataset, and some features like eCon seem to require precomputation that is not documented anywhere. Here is the line that's failing:
https://github.com/neulab/InterpretEval/blob/master/interpretEval/tensorEvaluation-ner.py#L294

Could you give some guidance?

**Comment by jlfu** [comment]
Hi,

Because the calculation of some attributes is time-consuming, we removed these codes. If it is necessary, we can add it.

**Comment by neubig** [comment]
Related to https://github.com/neulab/InterpretEval/issues/7 , it'd be nice to have an example of how to runt he code on a new dataset. As-is, the code crashes at the point I listed above, so I'm not able to apply the code to a new dataset.

**Comment by neubig** [comment]
This has been fixed.
