### ISSUE TITLE
Proposal to make adding new datasets easier

### ISSUE THREAD

**Issue by neubig** [neulab/InterpretEval#7]
Hi,

I have a proposal to make adding new datasets easier:

1. For each dataset, consolidate the location of all the related data into something like:

    data/ner/conll03/conll03.conf
    data/ner/conll03/data
    data/ner/conll03/results
    data/ner/conll03/precomputed

so it's clear where all the data is.

2. Show an example of going from just the "data" and "results" directory (i.e. stuff that's in easy-to-interpret formats such as CoNLL format) to a full report, including the precomputation.

What do you think? This would be very helpful and hopefully not too much work?

**Comment by jlfu** [comment]
Hi,
Thanks for your helpful suggestion. Yes, putting the related data together will make the structure of the repository more clear. And, actually, this change will not take too much time.

**Comment by neubig** [comment]
Cool, this would be really helpful for something with an upcoming deadline on 2/5. If you'd have time to help out that'd be greatly appreciated, otherwise I'll try it myself.

**Comment by jlfu** [comment]
Yes, Pengfei and I will try our best to help out. According to your suggestions (a few days ago), we can quickly group language by its language family, which will make it easy to further analyze according to the language family. What's more, Pengfei and I will give some interesting analyses/observations and share them with you on Wednesday.

**Comment by neubig** [comment]
Oh, BTW, I think we're talking about different deadlines for 2/5. I just want to run the software myself, independent of the paper that we're preparing together...

**Comment by jlfu** [comment]
Sorry for the misunderstanding. 😅
Ok, I see. It is my pleasure to help out 😄.  I can optimize this project before your deadline (2/5) since I have enough flexible time in February. And, thanks for the useful suggestion.

**Comment by neubig** [comment]
Seems like this is now fixed, thanks @jlfu !
